[package]
name = "crystal-marie"
version = "0.1.0"
edition = "2021"





# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
derive-new = "0.5.9"
easy-ext = "1.0.1"
enum = "0.0.0"
enum_unwrapper = "0.1.2"


